default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: bigquerytry-477123
      dataset: jaffle_shop_bq
      threads: 4
      keyfile: /Users/kliu/recceAll/jaffle-shop-bigquery/dbt-ser-creds.json
